# This file is a template, and might need editing before it works on your project.
image: python:2.7

stages:
  - prepare
  - benchmark

before_script:
  - python -V # Print out python version for debugging
  - apt update && apt install time
  - make 3rd

test:
  stage: prepare
  script: make test

compile:
  stage: prepare
  script: make run
  artifacts:
    paths: 
      - bin/e2
      - e2-*.log

benchmark:
  stage: benchmark
  script: cat e2-*.log
