# This file is a template, and might need editing before it works on your project.
image: python:latest

stages:
  - prepare
  - benchmark

before_script:
  - python -V # Print out python version for debugging
  - make 3rd

test:
  stage: prepare
  script: make test

compile:
  stage: prepare
  script: make bin/e2
  artifacts:
    paths: 
      - bin/e2

benchmark:
  stage: benchmark
  script: time make run
  artifacts:
    paths:
      - e2.log

