git:
  depth: 3

matrix:
  include:
    - language: python
      python: 3.6
      script: make test
    - language: c
      script:
        - make bin/e2
        - make run
        - cat e2-*.log
    - language: c
      script:
        - make bin/e2-handmade
        - make run-handmade
        - cat e2-*.log
